### ISSUE TITLE
Update using pydoc3 instead of pydoc

### ISSUE THREAD

**Issue by marcuskammer** [tpict/vim-ftplugin-python#10]
The following code is using pydoc, which is Python version 2.

`" First time: try finding "pydoc".
if !exists('g:pydoc_executable')
    if executable('pydoc')
        let g:pydoc_executable = 1
    else
        let g:pydoc_executable = 0
    endif
endif
" If "pydoc" was found use it for keywordprg.
if g:pydoc_executable
    setlocal keywordprg=pydoc
endif
`

Most of the modern Operating systems have Python version 3 installed and most of the Python Developer are using Python version 3. The equivalent of pydoc command under Python3 is called 'pydoc3'.

I suggest to update the ftplugin with the following code:

`if has('python3')
       if !exists('g:pydoc_executable')
    if executable('pydoc3')
        let g:pydoc_executable = 1
    else
        let g:pydoc_executable = 0
    endif
endif
" If "pydoc" was found use it for keywordprg.
if g:pydoc_executable
    setlocal keywordprg=pydoc3
endif
endif
`

Thank you!

**Comment by tpict** [comment]
Good catch 😄 I'll add that in.

**Comment by craigmac** [comment]
Caution: On Windows there is no installed default pydoc3 with Python 3.7.3 from python.org. Running `where pydoc3` and `where pydoc` returns nothings. To use pydoc3 you must modify your path or run with an absolute path to the pydoc3.py e.g., `python C:\Python37\Tools\scripts\pydoc3.py {keyword}`

However, by default `python -m pydoc {keyword}` (notice pydoc version is not pydoc3) does work.

**Comment by tpict** [comment]
@saltycraig see https://github.com/tpict/vim-ftplugin-python/pull/11 - I think this should work for both Windows and Unix users
