### ISSUE TITLE
Question python version supported.

### ISSUE THREAD

**Issue by tecis** [tpict/vim-ftplugin-python#16]
Is Python3 syntax natively supported?

**Comment by tpict** [comment]
This repository doesn't contain any syntax highlighting configuration, but Vim does have built-in support for syntax constructs added in Python 3. [You can find the syntax file here](https://github.com/vim/vim/blob/3044324e8dccd470bd854cf7d9457232cc9c220e/runtime/syntax/python.vim)

**Comment by tecis** [comment]
@tpict Thank you for the response. Seems I was confused.
