### ISSUE TITLE
][, [], ]M, and [M motions do not work

### ISSUE THREAD

**Issue by bgx90** [tpict/vim-ftplugin-python#8]
][, [], ]M, and [M motions do not work due to incorrect arguments being passed to the `<SID>Python_jump` function calls in the mappings; 0 is being passed to the as the count parameter and v:count1 is being passed as a:1 causing searches to not be performed for these motions.  After examining the `<SID>Python_jump` function, I came to the conclusion that the intention was to pass v:count1 to the count parameter and 0 to a:1.  After making this change to the mappings for the misbehaving motions, they work as expected.

For example, this is the original mapping for ][ in normal mode which does not work:
`execute "nnoremap <silent> <buffer> ][ :call <SID>Python_jump('n', '". b:next_endtoplevel."', 'W', 0, v:count1)<cr>"`

][ works in normall mode after reversing the order of the last two arguments in the call to `<SID>Python_jump`:
`execute "nnoremap <silent> <buffer> ][ :call <SID>Python_jump('n', '". b:next_endtoplevel."', 'W', v:count1, 0)<cr>"`

I was able to get the rest of the above mentioned motions working by making the same change to the argument lists of the function calls in each of their mappings.

Since I have installed vim via the Debian testing repository, I am using an older version of the python ftplugin (Last Change:	Sun, 15 April 2018), but I see that this bug exists in the latest version available as well.

**Comment by tpict** [comment]
Good catch, thanks! Looks like the arguments weren't added in the right order when count prefix support was added: https://github.com/tpict/vim-ftplugin-python/commit/71958218302d088bbd6b669ff45e53949d677b7b

Would you like to open a pull request for this fix?

**Comment by bgx90** [comment]
Sure, what is you workflow for that?  Do I create a banch on your repository or make a fork of my own?

**Comment by tpict** [comment]
If you make your own fork, you'll have an option to select a branch from it when you create the PR :smile:

**Comment by liberforce** [comment]
Hum, I'm using Ubuntu 20.04 with the python.vim from 17 Mar 2019, but these motions are still broken for me. They either send me at the end of the file, or stop on closing brackets....
Do you have a file you use for testing, so I can check if it's not my python file that makes it fail?

**Comment by tpict** [comment]
I don't have a particular file I test against, but these trivial classes work correctly for me:
```py
class Test:
    def method_1(self):
        some_var = 1
        pass

    def method_2(self):
        some_var = 1
        pass

class Test2:
    def method_1(self):
        some_var = 1
        pass

    def method_2(self):
        some_var = 1
        pass
```
Do you get the same behavior if you start vim with `vim -u NONE`?

**Comment by liberforce** [comment]
```
class Test1:
    def method_1(self):
        some_var = 1
        pass

    def method_2(self):
        some_var = 1
        pass

class Test2:
    _prop1 = None

    @property
    def prop1(self):
        return self._prop1

    @prop1.setter
    def prop1(self, value):
        self._prop1 = value

class Test3:
    def method_1(self):
        some_var = 1
        pass

    def method_2(self):
        some_var = 1
        pass

```
Decorators seem to confuse the moves like `[M` and `]M`. You end up on the decorator line instead of the last line of the method on class `Test2`. I have a bigger file where I can see more problems, but that's production code I can't share. I'll try to narrow it down with more code examples if that can help.

**Comment by tpict** [comment]
Yeah I see that. Thanks for the repro. I'm probably not going to have time to solve this myself until next month, but if you'd like to give it a shot, take a look at the regex definitions starting on line 49. I think you just need to add a pattern for decorators in addition to the class/function/method declaration keywords. Feel free to open a new issue for this specific issue so it doesn't get lost!
